In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,29)

array([29, 29, 29, 29, 29, 29, 29, 29, 29, 29])

In [6]:
a = np.array([1, 2, 3, 4, 7, 12])

In [7]:
a

array([ 1,  2,  3,  4,  7, 12])

In [8]:
a[2]

np.int64(3)

In [10]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [12]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ])

In [14]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
n[0, 1]

np.int64(2)

In [16]:
n[0, 1] = 20

In [17]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [20]:
np.random.rand(5, 2)

array([[0.66738481, 0.03089409],
       [0.69917236, 0.9052507 ],
       [0.9107451 , 0.41392822],
       [0.41118123, 0.47928062],
       [0.12424804, 0.82143569]])

In [21]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [22]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [29]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [35]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [34]:
a+1

array([1, 2, 3, 4, 5])

In [32]:
a*2

array([0, 2, 4, 6, 8])

In [36]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [37]:
a+b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [41]:
a

array([0, 1, 2, 3, 4])

In [40]:
a >= 2

array([False, False,  True,  True,  True])

In [42]:
a > b

array([False, False,  True,  True,  True])

In [43]:
a[a>b]

array([2, 3, 4])

In [44]:
a.min()

np.int64(0)

In [47]:
a.sum()

np.int64(10)

In [48]:
a.mean()

np.float64(2.0)

In [49]:
a.std()

np.float64(1.4142135623730951)

In [50]:
n.min()

np.int64(1)